# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5571235515bb5bc2999b3c2b5893a71b14c7eb64a3193da00e17879f3f894d762e1e239b1d3e8fc575b90e07dd7273fb550e347578953a25faba056e358f0598

test:
  secret_key_base: 246d37b3227bc6330a603c3d1d6d59bdf69093129b1f83c2ae8c908d04f50ea8f0e98bde23c9261e389adc3acf4a46391f90ac5716299151da55f54abab975c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
